FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV REACT_APP_GOOGLE_APP_ID $REACT_APP_GOOGLE_APP_ID
ENV REACT_APP_GOOGLE_API_KEY $REACT_APP_GOOGLE_API_KEY
ENV REACT_APP_SERVER_BASE_URL $REACT_APP_SERVER_BASE_URL

RUN npm run build

EXPOSE 8080

CMD npx serve build