FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV REACT_APP_GOOGLE_APP_ID $_REACT_APP_GOOGLE_APP_ID
ENV REACT_APP_GOOGLE_API_KEY $_REACT_APP_GOOGLE_API_KEY
ENV REACT_APP_SERVER_BASE_URL $_REACT_APP_SERVER_BASE_URL

RUN npm run build

RUN npm install -g serve

EXPOSE 8080

CMD serve -s build